### ISSUE TITLE
validation-method is dns-generic.

### ISSUE THREAD

**Issue by huytn** [open-mpic/aws-lambda-python#2]
https://github.com/open-mpic/open-mpic-specification/blob/b04af663e493300cad8dab61400d6bd56ac69129/openapi.yaml#L244

https://github.com/open-mpic/aws-lambda-python/blob/fd5c4d4e8fb62e24cf269697f9f7d4d1c8a9d51a/lambda_validator/lambda_function.py#L54

I found an issue, as spec describes it should be:

`name_to_resolve = f'{challenge_prefix}.{identifier}' if len(challenge_prefix) > 0 else f'{identifier}.'`

And controller function could not handle error response.
<img width="994" alt="Screenshot 2024-07-19 at 14 27 25" src="https://github.com/user-attachments/assets/7764e023-a677-4497-b393-4061c6e690f0">

**Comment by birgelee** [comment]
I pushed a fix for this in 3ecfa02 

I used the line you proposed with a small change: I removed the trailing .

so
`else f'{identifier}.'` -> `else f'{identifier}'`

This was for consistency because none of the other identifier values have a trailing . added when passed to the DNS library. If there is a reason to add the trailing dot here or elsewhere, let me know.

**Comment by birgelee** [comment]
Also, controller currently does not have proper error handling for errors originated by remote perspectives. Thus, any error generated by a remote perspective will propagate up and cause a 500 Internal Server Error. This will be fixed shortly.
